In [1]:
import pandas as pd
from os import listdir

In [2]:
filenames = listdir('CMIP6_tas_landsea')

In [3]:
res = map(lambda x: x.split('_'), filenames)

In [4]:
scenarios = ['historical', 'ssp126', 'ssp245', 'ssp370', 'ssp585']

In [5]:
filename = [file for file in listdir('CMIP5_tas_landsea') if ('EC-Earth3' in file.split('_')) and ('ssp126' in file) ]

In [6]:
filename

[]

In [7]:
def get_model_name(filename):
    return filename.split('_')[1]

In [8]:
print(get_model_name('CMIP5_HadGEM3-GC31-LL_ssp245_r1i1p1f3.csv'))

HadGEM3-GC31-LL


In [9]:
def scenario_df(scenario):
    frames = []
    filenames = [file for file in listdir('CMIP6_tas_landsea') if scenario in file]
    for file in filenames:
        model_name = get_model_name(file)
        df = pd.read_csv('CMIP6_tas_landsea/' + file, header=15, usecols=['date', 'world'])
        df['scenario'] = scenario
        df['model'] = model_name
        frames.append(df)
    return pd.concat(frames, ignore_index=True)
    


In [10]:
ssp126 = scenario_df('ssp126')
ssp245 = scenario_df('ssp245')
ssp370 = scenario_df('ssp370')
ssp585 = scenario_df('ssp585')

In [11]:
def dateify_proj(frames):
    for frame in frames:
        frame['date'] = pd.to_datetime(frame['date'], format='%Y-%m')
all_scenarios = [ssp126, ssp245, ssp370, ssp585]
dateify_proj(all_scenarios)

In [12]:
bins = [2021, 2041, 2061, 2081, 2101]
labels = ['2021-2040', '2041-2060', '2061-2080', '2081-2100']
models = ['UKESM1-0-LL', 'CMCC-CM2-SR5', 'MPI-ESM1-2-HR', 'NorESM2-MM', 'INM-CM4-8',
 'ACCESS-ESM1-5', 'CNRM-CM6-1', 'MRI-ESM2-0', 'NESM3', 'CESM2', 'ACCESS-CM2',
 'MPI-ESM1-2-LR', 'EC-Earth3-Veg', 'IITM-ESM', 'MIROC6', 'BCC-CSM2-MR',
 'INM-CM5-0', 'AWI-CM-1-1-MR', 'FGOALS-g3', 'EC-Earth3', 'NorESM2-LM',
 'GFDL-ESM4', 'KACE-1-0-G', 'CNRM-ESM2-1', 'MIROC-ES2L', 'CAMS-CSM1-0',
 'CanESM5', 'IPSL-CM6A-LR', 'CNRM-CM6-1-HR', 'HadGEM3-GC31-LL', 'KIOST-ESM',
 'CESM2-WACCM']


In [13]:
def groups_20_year(frame):
    frame['period'] = pd.cut(frame['date'].dt.year, bins=bins, labels=labels, right=False)
    return frame.groupby(['scenario', 'model', 'period'])['world'].mean().reset_index()


In [14]:
ssp126Avgs = groups_20_year(ssp126).round(2)
ssp245Avgs = groups_20_year(ssp245).round(2)
ssp370Avgs = groups_20_year(ssp370).round(2)
ssp585Avgs = groups_20_year(ssp585).round(2)

/tmp/ipykernel_2654477/2331576031.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return frame.groupby(['scenario', 'model', 'period'])['world'].mean().reset_index()
/tmp/ipykernel_2654477/2331576031.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return frame.groupby(['scenario', 'model', 'period'])['world'].mean().reset_index()
/tmp/ipykernel_2654477/2331576031.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.


In [15]:
[ssp126Avgs, ssp245Avgs, ssp370Avgs, ssp585Avgs]

[    scenario          model     period  world
 0     ssp126     ACCESS-CM2  2021-2040  15.39
 1     ssp126     ACCESS-CM2  2041-2060  15.99
 2     ssp126     ACCESS-CM2  2061-2080  16.20
 3     ssp126     ACCESS-CM2  2081-2100  16.27
 4     ssp126  ACCESS-ESM1-5  2021-2040  16.02
 ..       ...            ...        ...    ...
 123   ssp126     NorESM2-MM  2081-2100  15.22
 124   ssp126    UKESM1-0-LL  2021-2040  15.20
 125   ssp126    UKESM1-0-LL  2041-2060  15.76
 126   ssp126    UKESM1-0-LL  2061-2080  15.97
 127   ssp126    UKESM1-0-LL  2081-2100  16.06
 
 [128 rows x 4 columns],
     scenario          model     period  world
 0     ssp245     ACCESS-CM2  2021-2040  15.37
 1     ssp245     ACCESS-CM2  2041-2060  16.18
 2     ssp245     ACCESS-CM2  2061-2080  16.76
 3     ssp245     ACCESS-CM2  2081-2100  17.18
 4     ssp245  ACCESS-ESM1-5  2021-2040  16.06
 ..       ...            ...        ...    ...
 131   ssp245     NorESM2-MM  2081-2100  16.00
 132   ssp245    UKESM1-0-LL  202

In [16]:
ssp126

date   world scenario        model     period
0     2015-01-01  12.338   ssp126  UKESM1-0-LL        NaN
1     2015-02-01  12.530   ssp126  UKESM1-0-LL        NaN
2     2015-03-01  13.251   ssp126  UKESM1-0-LL        NaN
3     2015-04-01  14.239   ssp126  UKESM1-0-LL        NaN
4     2015-05-01  15.185   ssp126  UKESM1-0-LL        NaN
...          ...     ...      ...          ...        ...
32995 2100-08-01  18.024   ssp126  CESM2-WACCM  2081-2100
32996 2100-09-01  17.271   ssp126  CESM2-WACCM  2081-2100
32997 2100-10-01  16.414   ssp126  CESM2-WACCM  2081-2100
32998 2100-11-01  15.591   ssp126  CESM2-WACCM  2081-2100
32999 2100-12-01  14.885   ssp126  CESM2-WACCM  2081-2100

[33000 rows x 5 columns]

In [17]:
historical = scenario_df('historical').round(2)

In [18]:
historical

date  world    scenario             model
0      1850-01  10.96  historical       UKESM1-0-LL
1      1850-02  11.18  historical       UKESM1-0-LL
2      1850-03  12.15  historical       UKESM1-0-LL
3      1850-04  13.22  historical       UKESM1-0-LL
4      1850-05  14.19  historical       UKESM1-0-LL
...        ...    ...         ...               ...
60475  2014-08  16.69  historical  EC-Earth3-Veg-LR
60476  2014-09  15.94  historical  EC-Earth3-Veg-LR
60477  2014-10  14.87  historical  EC-Earth3-Veg-LR
60478  2014-11  13.51  historical  EC-Earth3-Veg-LR
60479  2014-12  12.72  historical  EC-Earth3-Veg-LR

[60480 rows x 4 columns]

In [19]:
historical_bins = [1850, 1900]
historical_label = ['1850-1900']
historical['date'] = historical['date'] = pd.to_datetime(historical['date'], format='%Y-%m')
historical['period'] = pd.cut(historical['date'].dt.year, bins=historical_bins, labels=historical_label, right=False)
historicalAvgs = historical.groupby(['scenario', 'model', 'period'])['world'].median().reset_index()

/tmp/ipykernel_2654477/1299099412.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  historicalAvgs = historical.groupby(['scenario', 'model', 'period'])['world'].median().reset_index()


In [20]:
historicalAvgs

scenario             model     period   world
0   historical        ACCESS-CM2  1850-1900  13.835
1   historical     ACCESS-ESM1-5  1850-1900  14.540
2   historical     AWI-CM-1-1-MR  1850-1900  13.755
3   historical       BCC-CSM2-MR  1850-1900  14.820
4   historical       CAMS-CSM1-0  1850-1900  13.795
5   historical             CESM2  1850-1900  14.020
6   historical       CESM2-WACCM  1850-1900  13.835
7   historical      CMCC-CM2-SR5  1850-1900  14.105
8   historical        CNRM-CM6-1  1850-1900  12.880
9   historical     CNRM-CM6-1-HR  1850-1900  12.325
10  historical       CNRM-ESM2-1  1850-1900  13.640
11  historical           CanESM5  1850-1900  13.535
12  historical         EC-Earth3  1850-1900  13.940
13  historical     EC-Earth3-Veg  1850-1900  13.530
14  historical  EC-Earth3-Veg-LR  1850-1900  13.535
15  historical         FGOALS-g3  1850-1900  12.810
16  historical          GFDL-CM4  1850-1900  12.765
17  historical         GFDL-ESM4  1850-1900  13.495
18  historical   HadGEM3-GC31-LL  1850-1900  13.710
19  historical          IITM-ESM  1850-1900  13.990
20  historical         INM-CM4-8  1850-1900  13.310
21  historical         INM-CM5-0  1850-1900  13.140
22  historical      IPSL-CM6A-LR  1850-1900  12.875
23  historical        KACE-1-0-G  1850-1900  13.550
24  historical         KIOST-ESM  1850-1900  12.400
25  historical        MIROC-ES2L  1850-1900  14.965
26  historical            MIROC6  1850-1900  15.120
27  historical     MPI-ESM1-2-HR  1850-1900  13.940
28  historical     MPI-ESM1-2-LR  1850-1900  13.540
29  historical        MRI-ESM2-0  1850-1900  13.745
30  historical             NESM3  1850-1900  13.665
31  historical        NorESM2-LM  1850-1900  14.505
32  historical        NorESM2-MM  1850-1900  13.920
33  historical           TaiESM1  1850-1900  13.955
34  historical       UKESM1-0-LL  1850-1900  13.450

In [21]:
ssp126merged = pd.merge(ssp126Avgs, historicalAvgs[['model', 'world']], on='model', suffixes=('', '_historical'))
ssp245merged = pd.merge(ssp245Avgs, historicalAvgs[['model', 'world']], on='model', suffixes=('', '_historical'))
ssp370merged = pd.merge(ssp370Avgs, historicalAvgs[['model', 'world']], on='model', suffixes=('', '_historical'))
ssp585merged = pd.merge(ssp585Avgs, historicalAvgs[['model', 'world']], on='model', suffixes=('', '_historical'))


In [22]:
def collect_changes(frame):
    frame['changed'] = frame['world'] - frame['world_historical'] - 0.25
    return frame.drop(columns=['world_historical'])
mergeds = [ssp126merged, ssp245merged, ssp370merged, ssp585merged]

changeds = map(collect_changes, mergeds)

In [23]:
for frame in changeds:
    print(frame)

    scenario          model     period  world  changed
0     ssp126     ACCESS-CM2  2021-2040  15.39    1.305
1     ssp126     ACCESS-CM2  2041-2060  15.99    1.905
2     ssp126     ACCESS-CM2  2061-2080  16.20    2.115
3     ssp126     ACCESS-CM2  2081-2100  16.27    2.185
4     ssp126  ACCESS-ESM1-5  2021-2040  16.02    1.230
..       ...            ...        ...    ...      ...
123   ssp126     NorESM2-MM  2081-2100  15.22    1.050
124   ssp126    UKESM1-0-LL  2021-2040  15.20    1.500
125   ssp126    UKESM1-0-LL  2041-2060  15.76    2.060
126   ssp126    UKESM1-0-LL  2061-2080  15.97    2.270
127   ssp126    UKESM1-0-LL  2081-2100  16.06    2.360

[128 rows x 5 columns]
    scenario          model     period  world  changed
0     ssp245     ACCESS-CM2  2021-2040  15.37    1.285
1     ssp245     ACCESS-CM2  2041-2060  16.18    2.095
2     ssp245     ACCESS-CM2  2061-2080  16.76    2.675
3     ssp245     ACCESS-CM2  2081-2100  17.18    3.095
4     ssp245  ACCESS-ESM1-5  2021-2040  1

In [24]:
import matplotlib.pyplot as plt

In [25]:
periods = ['2021-2040', '2041-2060', '2061-2080', '2081-2100']

def plot_hists(frame):
    scenario = frame['scenario'][0]
    for period in periods:
        plt.figure(figsize=(8, 6))
        period_data = frame[frame['period'] == period]
        n, bins, patches = plt.hist(period_data['changed'], bins=10, edgecolor='black', alpha=0.7, density=True)
        plt.title('Distribution of predicted changes for scenario ' + scenario + ' during ' + period, fontsize=14)
        bin_labels = [f"{bins[i]:.1f}" for i in range(len(bins))]
        plt.xticks(bins, bin_labels, rotation=45)
        plt.xlabel('Amount of change', fontsize=10)
        plt.ylabel('Density', fontsize=10)
        plt.show()

In [26]:
import numpy as np

ssp126merged['changed']

0      1.305
1      1.905
2      2.115
3      2.185
4      1.230
       ...  
123    1.050
124    1.500
125    2.060
126    2.270
127    2.360
Name: changed, Length: 128, dtype: float64

In [27]:
methods = ['inverted_cdf','averaged_inverted_cdf','closest_observation','interpolated_inverted_cdf','hazen','weibull','linear','median_unbiased', 'normal_unbiased']
period = '2081-2100'
for method in methods:
    print("Method: " + method)
    print("ssp126")
    print(np.percentile(ssp126merged[ssp126merged['period'] == period]['changed'], [5, 50, 95], axis=None, method=method))
    print("ssp245")
    print(np.percentile(ssp245merged[ssp245merged['period'] == period]['changed'], [5, 50, 95], axis=None, method=method))
    print("ssp370")
    print(np.percentile(ssp370merged[ssp370merged['period'] == period]['changed'], [5, 50, 95], axis=None, method=method))
    print("ssp585")
    print(np.percentile(ssp585merged[ssp585merged['period'] == period]['changed'], [5, 50, 95], axis=None, method=method))
ssp126merged[ssp126merged['period'] == '2081-2100']['changed'].mean()

Method: inverted_cdf
ssp126
[1.05  1.715 2.605]
ssp245
[1.83  2.665 3.69 ]
ssp370
[2.615 3.68  5.16 ]
ssp585
[3.39  4.415 6.2  ]
Method: averaged_inverted_cdf
ssp126
[1.05  1.72  2.605]
ssp245
[1.83 2.67 3.69]
ssp370
[2.615  3.6875 5.16  ]
ssp585
[3.39 4.44 6.2 ]
Method: closest_observation
ssp126
[1.05  1.715 2.545]
ssp245
[1.83  2.665 3.625]
ssp370
[2.465 3.68  5.16 ]
ssp585
[3.39  4.415 5.85 ]
Method: interpolated_inverted_cdf
ssp126
[1.032 1.715 2.569]
ssp245
[1.8195 2.665  3.6445]
ssp370
[2.54 3.68 4.92]
ssp585
[3.2475 4.415  5.955 ]
Method: hazen
ssp126
[1.0525 1.72   2.599 ]
ssp245
[1.831 2.67  3.677]
ssp370
[2.615  3.6875 5.16  ]
ssp585
[3.391 4.44  6.13 ]
Method: weibull
ssp126
[1.03425 1.72    2.62775]
ssp245
[1.82125 2.67    3.75375]
ssp370
[2.5475  3.6875  5.38725]
ssp585
[3.27125 4.44    6.33625]
Method: linear
ssp126
[1.06375 1.72    2.572  ]
ssp245
[1.83325 2.67    3.64775]
ssp370
[2.66675 3.6875  4.944  ]
ssp585
[3.39325 4.44    5.9725 ]
Method: median_unbiased
ssp126
[

1.72578125

In [28]:
import math
def comppercentile(arr, p):
    sorted = np.sort(arr)
    rank = ((p/100) * (len(arr)-1))+1
    print("Rank: " + str(rank))
    if rank == math.floor(rank):
        return arr.iloc[rank]
    else:
        print("Interpolating: ")
        x1 = math.floor(rank)
        x2 = math.ceil(rank)
        return arr.iloc[x1] + (rank - math.floor(rank))*(arr.iloc[x2] - arr.iloc[x1])

for period in periods:
    print(comppercentile(ssp245merged[ssp245merged['period'] == period]['changed'], 50))
        

Rank: 17.5
Interpolating: 
-0.040000000000000036
Rank: 17.5
Interpolating: 
-0.04499999999999993
Rank: 17.5
Interpolating: 
-0.03500000000000281
Rank: 17.5
Interpolating: 
0.012500000000000178


In [29]:
def likelihood_of_two(arr):
    bigger = [x for x in arr if x >= 2]
    return len(bigger)/len(arr)
len(ssp245merged[ssp245merged['period'] == '2081-2100']['changed'])
filtered = [x for x in (ssp245merged[ssp245merged['period'] == '2081-2100']['changed']) if x >= 2]

In [30]:
import re

with open('../examples/fluid/example/text-viz/datasets/ssp126.fld', 'w') as text_file:
    text_file.write(re.sub(r'"([^"]+)":', r'\1: ', ssp126merged.drop('scenario', axis=1).round(2).to_json(orient='records', indent=2)))

with open('../examples/fluid/example/text-viz/datasets/ssp245.fld', 'w') as text_file:
    text_file.write(re.sub(r'"([^"]+)":', r'\1: ', ssp245merged.drop('scenario', axis=1).round(2).to_json(orient='records', indent=2)))

with open('../examples/fluid/example/text-viz/datasets/ssp370.fld', 'w') as text_file:
    text_file.write(re.sub(r'"([^"]+)":', r'\1: ', ssp370merged.drop('scenario', axis=1).round(2).to_json(orient='records', indent=2)))

with open('../examples/fluid/example/text-viz/datasets/ssp585.fld', 'w') as text_file:
    text_file.write(re.sub(r'"([^"]+)":', r'\1: ', ssp585merged.drop('scenario', axis=1).round(2).to_json(orient='records', indent=2)))

In [31]:
len(filtered)

30

In [32]:
ssp245merged[ssp245merged['period'] == '2081-2100']['changed']

3      3.095
7      2.720
11     2.635
15     2.130
19     1.795
23     2.980
27     3.015
31     3.315
35     2.890
39     3.625
43     2.820
47     3.945
51     2.880
55     3.400
59     2.765
63     2.110
67     2.665
71     1.905
75     3.460
79     2.150
83     2.020
87     2.060
91     3.325
95     3.560
99     2.520
103    2.235
107    2.060
111    2.150
115    2.160
119    2.435
123    2.675
127    1.835
131    1.830
135    3.690
Name: changed, dtype: float64